import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbars from "./components/Navbars";
import ProductLists from "./components/ui/List/ProductLists";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className=" bg-slate-950 flex items-center justify-center h-14">
          <div className="flex items-center justify-center flex-auto">
            <h1 className="text-white ml-40">Winter Sale For All Swim Suits And Free Express Delivery - OFF 50%!</h1>
            <h1 className="relative text-white cursor-pointer ml-4 transition-all duration-300 ease-in-out 
              before:absolute before:bottom-0 before:left-0 before:h-[2px] 
              before:w-0 before:bg-white before:transition-all before:duration-300 
              hover:before:w-full">
              Trade Now
            </h1>

          </div>
          <div className="">
            <p className=" text-white mr-20">English</p>
          </div>
        </header>
        <header className="flex justify-center top-0 sticky overflow-hidden items-center h-32 bg-black bg-opacity-0 border-b-2 transition-all group">
          <div className="absolute inset-0 h-full w-full bg-black bg-opacity-0 blur-sm z-0"></div>
          <div className="relative z-10">
            <Navbars />
          </div>
        </header>
        <aside className=" sticky top-0 left-0 w-20 hover:w-52 transition-all duration-300 border-x-2 px-2 overflow-hidden py-5">
          <ProductLists />
        </aside>
        {children}
        <footer className=" flex items-center align-middle bg-cyan-950 h-32 justify-center">
          <p className="text-center text-white">All rights reserved © 2024 Cryptotality</p>
        </footer>
      </body>
    </html>
  );
}
