import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbars from "./components/Navbars";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className=" flex justify-center items-center  h-32 bg-cyan-950">
          <h1 className="text-left ml-3">Byte Blossoms</h1>
          <div className="mx-auto">
            <Navbars />
          </div>
        </header>
        {children}
        <footer className=" flex items-center align-middle bg-cyan-950 h-32 justify-center">
          <p className="text-center">All rights reserved © 2024 Crypto Buy</p>
        </footer>
      </body>
    </html>
  );
}
